### ISSUE TITLE
Create Cert Directory in icinga-client-config.yml fails

### ISSUE THREAD

**Issue by jbregman** [Shadow-Soft/ansible-icinga2-client#3]
fatal: [dev1.cyglass.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'pw_name'\n\nThe error appears to have been in '/etc/playbooks/icinga-client-config.yml': line 55, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      register: perm\n    - name: Creates cert directory\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'pw_name'"}

I had to comment out the owner and group attributes to get this to work.  

 - name: Creates cert directory                                                            
      file:                                                                                   
        path: "{{ cert_folder }}"                                                             
        state: directory                                                                      
        #owner: "{{ perm.stat.pw_name }}"                                                     
        #group: "{{ perm.stat.gr_name }}"            

The reason this fails is that "perm" is a file on the master.  The stat command one step before fails because its trying to stat a that same file on the client and so there is nothing in perm.stat.pw_name.

Not sure what the intention of setting the owner and group from the master to the client . The master is Icinga.  The client is my AMI...there is no guarantee that the users and groups are going to be the same.  Might be better just to have a variable for who the owner user and group should be on the client.

**Comment by dsuth1** [comment]
Hey Josh,
I think there is a bit of confusion here.  The user and group isn't set to that of the master.  It is sets to the permissions currently on the client.  Depending on what version of icinga you are on, the pki folder is in a different location.  Because we mirror the icinga version from the master on the client, the same pki folder path will inevitably be used.  To ensure the certs have the right perms, we set it to the folder permissions to those used on the client.  As for the failure.  It's patched in the latest version coming out later today
